### ISSUE TITLE
cleanup yumex_updater_systray

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#76]
A list of tasks to improve the code of the yumex_updater_systray

- [ ] is all the priority handling code need, when we just need the number of updates, we don't care what repo they comes from.
- [ ]  the update checker, should just return the number of updates, not a list of packages.

**Comment by timlau** [comment]
Hi @GloriousEggroll, could you please comment on the tasks above

**Comment by GloriousEggroll** [comment]
yes, the priority code is needed because it filters out unwanted packages from lower priority repos before the count is taken. If we dont do that it makes the count higher by adding those packages to the count.

in order to get the number of updates we need the list of packages - -thats where the count comes from. it refreshes the list then counts the items in the list.

**Comment by timlau** [comment]
OK, that's fine
