### ISSUE TITLE
Yumex service options don't show if the service is not running.

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#90]
If the yumex systray service is not running the options to control the service do not show in the yumex GUI. I think we need an enable/disable service toggle button (which would subsequently toggle the viewing of these options)

**Comment by timlau** [comment]
Yes, it is by design that the options is not shown when the service is not running.

As the updater is weak dependency sub package, the user can remove it, and no need to show options if it is not availabe.

But a better way to check if the updater is installed is properly needed.

I just took the easy road to use the existing function to check that the service was running, should check if the service was existing to hide/show the updater preferences or the lazy wy to just show them all the time.
